#!/bin/bash

# Logs
# tail -f /tmp/yabai_$USER.err.log
# tail -f /tmp/yabai_$USER.out.log

# Set up scripting addition with visudo
# echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai)"
# sudo visudo -f /private/etc/sudoers.d/yabai

# Source which machine you're running
source "$HOME/.config/machine.sh"
source "$HOME/.config/yabai/_displays.sh"

# Set up Home Configuration
home=$(yabai -m config \
  external_bar all:33:0 \
  mouse_follows_focus off \
  focus_follows_mouse autoraise \
  window_origin_display focused \
  window_placement second_child \
  window_zoom_persist on \
  window_shadow on \
  window_animation_duration 0.0 \
  window_animation_frame_rate 120 \
  window_opacity_duration 0.2 \
  active_window_opacity 0.98 \
  normal_window_opacity 0.65 \
  window_opacity on \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  top_padding 33 \
  bottom_padding 33 \
  left_padding 33 \
  right_padding 33 \
  window_gap 33 \
  layout bsp \
  mouse_modifier ctrl \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap)

# Set up Office Configuration
office=$home
LAYOUT=bsp

# Load Yabai
if [[ "$MACHINE" == 'home' ]]; then

  yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
  sudo yabai --load-sa

  # load config
  $home
else

  printf "\033[0;32mSkipping yabai scripting addition for work.\033[0m\n\n" # global settings
  yabai -m signal --add event=dock_did_restart action="sudo yabai"
  yabai

  # load office-adjusted config
  $office
  yabai -m config focus_follows_mouse off
  LAYOUT=bsp

fi

# If Home Clamshell Open
main_display=$(getMainDisplayUUID)
if [ "$main_display" == "$HOME_MACBOOK_UUID" ] || [ "$MACHINE" == 'office' ]; then
  LAYOUT=float
fi

yabai -m config layout $LAYOUT

# set up spaces after applying all configuration
source $HOME/.config/yabai/_spaces.sh

# add signals and manage applications
source $HOME/.config/yabai/_signals.sh
source $HOME/.config/yabai/_app-management.sh

printf "\033[0;32m✓ Yabai configuration loaded!\033[0m\n\n"
