#!/usr/bin/env sh
# Source which machine you're running
source "$HOME/.config/machine.sh"

# Useful keyboard scripts
# https://gist.github.com/dgrebb/d3ca843c61d9cabfdd30bf89976e454e

# view the last lines of the error log
# tail -f /tmp/yabai_$USER.err.log

# view the last lines of the debug log
# tail -f /tmp/yabai_$USER.out.log

if [[ "$MACHINE" != 'work' ]]; then
  sudo yabai --load-sa
  yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
else
  echo "Skipping yabai scripting addition for work."
fi

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# Source a list of displays and their properties
# https://github.com/koekeishiya/yabai/issues/1060#issuecomment-990431179
source $HOME/.config/yabai/displays.sh

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
# focus window after active display changes
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# fix window focus across displays
# yabai -m signal --add event=application_front_switched action="yabai -m window recent --opacity 0.8; yabai -m window --opacity 0.0"

yabai -m config \
  external_bar all:50:20 \
  mouse_follows_focus off \
  focus_follows_mouse autoraise \
  window_zoom_persist off \
  window_placement second_child \
  window_shadow on \
  window_opacity on \
  window_opacity_duration 0.2 \
  active_window_opacity 0.95 \
  normal_window_opacity 0.77 \
  window_animation_duration 0.3 \
  insert_feedback_color 0xff9dd274 \
  split_ratio 0.50 \
  auto_balance off \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  \
  top_padding 33 \
  bottom_padding 33 \
  left_padding 33 \
  right_padding 33 \
  window_gap 11

yabai -m config --space 1 top_padding 133 \
  bottom_padding 133 \
  left_padding 233 \
  right_padding 233

yabai -m config --space 2 top_padding 133 \
  bottom_padding 133 \
  left_padding 233 \
  right_padding 233

yabai -m config --space 3 top_padding 133 \
  bottom_padding 133 \
  left_padding 233 \
  right_padding 233 \
  window_gap 333

#
# setup spaces
#
for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 9)'); do
  yabai -m space --destroy 10
done

setup_space() {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  echo "setting up $idx space"

  yabai -m space "$idx" --label "$name"

  # if ( (idx >3 && idx <7)); then
  #   yabai -m space $idx --display 2
  # fi
  # if ( (idx >6)); then
  #   yabai -m space $idx --display 3
  # fi
}

# Fix layering issues with unmanaged windows
yabai -m rule --add app=".*" layer=normal

# Exclude problematic apps from being managed ----
yabai -m rule --add app="^(Nightscout Menu Bar|Verve|zoom.us|Zoom|Contrast|Min|Gifox|Bartender 5|GeekTool|CleanMyMac X|Airfoil|OmniFocusWidgetsExtension|Messages|Calendar|1Password Helper|1Password Helper (GPU)|Mail|Fantastical|Fantastical Helper|com.flexibits.fantastical.core.libical-XPC|OmniFocus|Music|Keyboard Maestro|TextExpander|Classic Color Meter|Digital Color Meter|Drafts|LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor|sketchybar)$" manage=off layer=below
yabai -m rule --add title="(Co(py|nnect)|Move|Info|Pref)" manage=off layer=below
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off layer=below
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off layer=below
yabai -m rule --add app="^(CopyClip 2|xScope|iStat Menus Status|com.bjango.istatmenus.weather|1Password Helper (Renderer)|1Password Browser Helper|^1Password$)$" manage=off layer=above

if [[ "$MACHINE" == 'work' ]]; then
  yabai -m config layout float
else
  yabai -m config layout bsp
fi

setup_space 1 music
setup_space 2 web
setup_space 3 office
setup_space 4 terminal
setup_space 5 other
setup_space 6 other
setup_space 7 code
setup_space 8 code
setup_space 9 project

# Assign apps to spaces
yabai -m rule --add app="^(Music)$" space=1
yabai -m rule --add app="^(Firefox)$" space=2
yabai -m rule --add app="^(Notion|Discord|Photoshop|Lightroom|Pym)$" space=3
yabai -m rule --add app="^(OmniFocus|Mail|Calendar)$" space=8
yabai -m rule --add app="^(iTerm)$" space=7
yabai -m rule --add app="^(Visual Studio Code)$" space=4

echo "yabai configuration loaded.."
