#!/usr/bin/env sh

# Source which machine you're running
source "$HOME/.config/machine.sh"

# Set up Home Configuration
home=$(yabai -m config \
  external_bar all:33:0 \
  mouse_follows_focus off \
  focus_follows_mouse autoraise \
  window_origin_display focused \
  window_placement second_child \
  window_zoom_persist on \
  window_shadow on \
  window_animation_duration 0.10 \
  window_animation_frame_rate 120 \
  window_opacity_duration 0.2 \
  active_window_opacity 0.95 \
  normal_window_opacity 0.65 \
  window_opacity on \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  top_padding 33 \
  bottom_padding 33 \
  left_padding 33 \
  right_padding 33 \
  window_gap 33 \
  layout bsp \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap)

# Set up Office Configuration
office=$home

# Load Yabai
if [[ "$MACHINE" == 'home' ]]; then
  sh $HOME/.config/yabai/_spaces.sh
  sh $HOME/.config/yabai/_signals.sh
  sh $HOME/.config/yabai/_app-management.sh
  yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
  sudo yabai --load-sa
  $home
  yabai -m config layout bsp
  yabai -m config --space 1 layout float
  yabai -m config --space 3 layout float
  yabai -m config --space 5 layout float
else
  printf "\033[0;32mSkipping yabai scripting addition for work.\033[0m\n\n" # global settings
  yabai -m signal --add event=dock_did_restart action="sudo yabai"
  sudo yabai
  $office
  yabai -m config layout float
fi

printf "\033[0;32m✓ Yabai configuration loaded!\033[0m\n\n"
